//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetArticlesRequest", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.A" +
        "rticlesApplicationService")]
    [System.SerializableAttribute()]
    public partial class GetArticlesRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetArticlesResponse", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.A" +
        "rticlesApplicationService")]
    [System.SerializableAttribute()]
    public partial class GetArticlesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.Article[] ArticlesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.Article[] Articles {
            get {
                return this.ArticlesField;
            }
            set {
                if ((object.ReferenceEquals(this.ArticlesField, value) != true)) {
                    this.ArticlesField = value;
                    this.RaisePropertyChanged("Articles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Article", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.A" +
        "rticlesApplicationService.Entities")]
    [System.SerializableAttribute()]
    public partial class Article : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.Comment[] CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.Comment[] Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageId {
            get {
                return this.ImageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageIdField, value) != true)) {
                    this.ImageIdField = value;
                    this.RaisePropertyChanged("ImageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.U" +
        "sersApplicationService.Entities")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comment", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.A" +
        "rticlesApplicationService.Entities")]
    [System.SerializableAttribute()]
    public partial class Comment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetArticleRequest", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.A" +
        "rticlesApplicationService")]
    [System.SerializableAttribute()]
    public partial class GetArticleRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ArticleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ArticleId {
            get {
                return this.ArticleIdField;
            }
            set {
                if ((this.ArticleIdField.Equals(value) != true)) {
                    this.ArticleIdField = value;
                    this.RaisePropertyChanged("ArticleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetArticleResponse", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.A" +
        "rticlesApplicationService")]
    [System.SerializableAttribute()]
    public partial class GetArticleResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.Article ArticleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.Article Article {
            get {
                return this.ArticleField;
            }
            set {
                if ((object.ReferenceEquals(this.ArticleField, value) != true)) {
                    this.ArticleField = value;
                    this.RaisePropertyChanged("Article");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateArticleRequest", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.A" +
        "rticlesApplicationService")]
    [System.SerializableAttribute()]
    public partial class CreateArticleRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateArticleResponse", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.A" +
        "rticlesApplicationService")]
    [System.SerializableAttribute()]
    public partial class CreateArticleResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteArticleRequest", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.A" +
        "rticlesApplicationService")]
    [System.SerializableAttribute()]
    public partial class DeleteArticleRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ArticleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ArticleId {
            get {
                return this.ArticleIdField;
            }
            set {
                if ((this.ArticleIdField.Equals(value) != true)) {
                    this.ArticleIdField = value;
                    this.RaisePropertyChanged("ArticleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteArticleResponse", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.A" +
        "rticlesApplicationService")]
    [System.SerializableAttribute()]
    public partial class DeleteArticleResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddCommentRequest", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.A" +
        "rticlesApplicationService")]
    [System.SerializableAttribute()]
    public partial class AddCommentRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ArticleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ArticleId {
            get {
                return this.ArticleIdField;
            }
            set {
                if ((this.ArticleIdField.Equals(value) != true)) {
                    this.ArticleIdField = value;
                    this.RaisePropertyChanged("ArticleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddCommentResponse", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.A" +
        "rticlesApplicationService")]
    [System.SerializableAttribute()]
    public partial class AddCommentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteCommentRequest", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.A" +
        "rticlesApplicationService")]
    [System.SerializableAttribute()]
    public partial class DeleteCommentRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ArticleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CommentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ArticleId {
            get {
                return this.ArticleIdField;
            }
            set {
                if ((this.ArticleIdField.Equals(value) != true)) {
                    this.ArticleIdField = value;
                    this.RaisePropertyChanged("ArticleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CommentId {
            get {
                return this.CommentIdField;
            }
            set {
                if ((this.CommentIdField.Equals(value) != true)) {
                    this.CommentIdField = value;
                    this.RaisePropertyChanged("CommentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteCommentResponse", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.A" +
        "rticlesApplicationService")]
    [System.SerializableAttribute()]
    public partial class DeleteCommentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FindImageRequest", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.I" +
        "magesApplicationsService")]
    [System.SerializableAttribute()]
    public partial class FindImageRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageId {
            get {
                return this.ImageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageIdField, value) != true)) {
                    this.ImageIdField = value;
                    this.RaisePropertyChanged("ImageId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FindImageResponse", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.I" +
        "magesApplicationsService")]
    [System.SerializableAttribute()]
    public partial class FindImageResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUserByNameRequest", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.U" +
        "sersApplicationService")]
    [System.SerializableAttribute()]
    public partial class GetUserByNameRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUserByNameResponse", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.U" +
        "sersApplicationService")]
    [System.SerializableAttribute()]
    public partial class GetUserByNameResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateNewUserRequest", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.U" +
        "sersApplicationService")]
    [System.SerializableAttribute()]
    public partial class CreateNewUserRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateNewUserResponse", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts.Commands.U" +
        "sersApplicationService")]
    [System.SerializableAttribute()]
    public partial class CreateNewUserResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArticlesServiceReference.IArticlesWebService")]
    public interface IArticlesWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/GetArticles", ReplyAction="http://tempuri.org/IArticlesWebService/GetArticlesResponse")]
        Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticlesResponse GetArticles(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticlesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/GetArticles", ReplyAction="http://tempuri.org/IArticlesWebService/GetArticlesResponse")]
        System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticlesResponse> GetArticlesAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticlesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/GetArticle", ReplyAction="http://tempuri.org/IArticlesWebService/GetArticleResponse")]
        Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticleResponse GetArticle(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/GetArticle", ReplyAction="http://tempuri.org/IArticlesWebService/GetArticleResponse")]
        System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticleResponse> GetArticleAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/CreateArticle", ReplyAction="http://tempuri.org/IArticlesWebService/CreateArticleResponse")]
        Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateArticleResponse CreateArticle(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateArticleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/CreateArticle", ReplyAction="http://tempuri.org/IArticlesWebService/CreateArticleResponse")]
        System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateArticleResponse> CreateArticleAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateArticleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/DeleteArticle", ReplyAction="http://tempuri.org/IArticlesWebService/DeleteArticleResponse")]
        Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteArticleResponse DeleteArticle(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteArticleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/DeleteArticle", ReplyAction="http://tempuri.org/IArticlesWebService/DeleteArticleResponse")]
        System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteArticleResponse> DeleteArticleAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteArticleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/AddComment", ReplyAction="http://tempuri.org/IArticlesWebService/AddCommentResponse")]
        Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.AddCommentResponse AddComment(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.AddCommentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/AddComment", ReplyAction="http://tempuri.org/IArticlesWebService/AddCommentResponse")]
        System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.AddCommentResponse> AddCommentAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.AddCommentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/DeleteComment", ReplyAction="http://tempuri.org/IArticlesWebService/DeleteCommentResponse")]
        Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteCommentResponse DeleteComment(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteCommentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/DeleteComment", ReplyAction="http://tempuri.org/IArticlesWebService/DeleteCommentResponse")]
        System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteCommentResponse> DeleteCommentAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteCommentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/FindImage", ReplyAction="http://tempuri.org/IArticlesWebService/FindImageResponse")]
        Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.FindImageResponse FindImage(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.FindImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/FindImage", ReplyAction="http://tempuri.org/IArticlesWebService/FindImageResponse")]
        System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.FindImageResponse> FindImageAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.FindImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/GetUserByName", ReplyAction="http://tempuri.org/IArticlesWebService/GetUserByNameResponse")]
        Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetUserByNameResponse GetUserByName(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetUserByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/GetUserByName", ReplyAction="http://tempuri.org/IArticlesWebService/GetUserByNameResponse")]
        System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetUserByNameResponse> GetUserByNameAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetUserByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/CreateNewUser", ReplyAction="http://tempuri.org/IArticlesWebService/CreateNewUserResponse")]
        Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateNewUserResponse CreateNewUser(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateNewUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticlesWebService/CreateNewUser", ReplyAction="http://tempuri.org/IArticlesWebService/CreateNewUserResponse")]
        System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateNewUserResponse> CreateNewUserAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateNewUserRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArticlesWebServiceChannel : Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.IArticlesWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArticlesWebServiceClient : System.ServiceModel.ClientBase<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.IArticlesWebService>, Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.IArticlesWebService {
        
        public ArticlesWebServiceClient() {
        }
        
        public ArticlesWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArticlesWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticlesWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticlesWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticlesResponse GetArticles(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticlesRequest request) {
            return base.Channel.GetArticles(request);
        }
        
        public System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticlesResponse> GetArticlesAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticlesRequest request) {
            return base.Channel.GetArticlesAsync(request);
        }
        
        public Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticleResponse GetArticle(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticleRequest request) {
            return base.Channel.GetArticle(request);
        }
        
        public System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticleResponse> GetArticleAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetArticleRequest request) {
            return base.Channel.GetArticleAsync(request);
        }
        
        public Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateArticleResponse CreateArticle(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateArticleRequest request) {
            return base.Channel.CreateArticle(request);
        }
        
        public System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateArticleResponse> CreateArticleAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateArticleRequest request) {
            return base.Channel.CreateArticleAsync(request);
        }
        
        public Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteArticleResponse DeleteArticle(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteArticleRequest request) {
            return base.Channel.DeleteArticle(request);
        }
        
        public System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteArticleResponse> DeleteArticleAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteArticleRequest request) {
            return base.Channel.DeleteArticleAsync(request);
        }
        
        public Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.AddCommentResponse AddComment(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.AddCommentRequest request) {
            return base.Channel.AddComment(request);
        }
        
        public System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.AddCommentResponse> AddCommentAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.AddCommentRequest request) {
            return base.Channel.AddCommentAsync(request);
        }
        
        public Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteCommentResponse DeleteComment(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteCommentRequest request) {
            return base.Channel.DeleteComment(request);
        }
        
        public System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteCommentResponse> DeleteCommentAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.DeleteCommentRequest request) {
            return base.Channel.DeleteCommentAsync(request);
        }
        
        public Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.FindImageResponse FindImage(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.FindImageRequest request) {
            return base.Channel.FindImage(request);
        }
        
        public System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.FindImageResponse> FindImageAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.FindImageRequest request) {
            return base.Channel.FindImageAsync(request);
        }
        
        public Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetUserByNameResponse GetUserByName(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetUserByNameRequest request) {
            return base.Channel.GetUserByName(request);
        }
        
        public System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetUserByNameResponse> GetUserByNameAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.GetUserByNameRequest request) {
            return base.Channel.GetUserByNameAsync(request);
        }
        
        public Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateNewUserResponse CreateNewUser(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateNewUserRequest request) {
            return base.Channel.CreateNewUser(request);
        }
        
        public System.Threading.Tasks.Task<Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateNewUserResponse> CreateNewUserAsync(Infotecs.MiniJournal.WcfServiceClient.ArticlesServiceReference.CreateNewUserRequest request) {
            return base.Channel.CreateNewUserAsync(request);
        }
    }
}
